### ISSUE TITLE
Issues with "Create Room" and "Join Room" buttons on the home screen

### ISSUE THREAD

**Issue by willmero** [jayehernandez/red-flags-clone#23]
Hey team!

This seems like an awesome project I'm interested in checking out. Trying to get up and famialirized with how everything functions, and I'm noticing that when landing on the home screen, the "Create Room" and the "Join Room" buttons are not actually taking you to the create/join screens. 

Looks to be the same behaviour on the deployed web app here:
red-flags-clone.vercel.app

Using the latest version of Chrome. Let me know if I'm missing something here!

Cheers,
Will

**Comment by jayehernandez** [comment]
Hey @willmero, thanks for your interest in this project!

Everything's still in development to a closed group of collaborators for now, which is why the demo site isn't working as expected yet. You can however, watch this repo for **releases** so that you'll be notified in the future when it's out.

![image](https://user-images.githubusercontent.com/13959651/115669761-362a9f80-a37b-11eb-9485-ccf24f8a4a88.png)

Thanks!!

**Comment by willmero** [comment]
Thanks so much @jayehernandez !

I'll certainly keep an eye out on this, and weigh in once the pool opens up.

Cheers,
Will
